<?php
require_once __DIR__ . '/../includes/db.php';

// Check if user is logged in
if (!isset($_SESSION['username'])) {
    die("Unauthorized access");
}

$type = $_GET['type'] ?? 'general';
$filename = "CentralPoint_Report_" . ucfirst($type) . "_" . date('Y-m-d') . ".xls";

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Pragma: no-cache");
header("Expires: 0");

echo '<table border="1">';

if ($type === 'applications') {
    echo '<tr><th colspan="3" style="background-color: #ec4899; color: white;">Total Applications Report</th></tr>';
    echo '<tr><th>App Name</th><th>Category</th><th>Status</th></tr>';
    // Dummy / Static representation since apps are manually listed in some parts
    // But we can fetch if there's a table. Usually these are portal tools.
    echo '<tr><td>Dashboard</td><td>Core</td><td>Active</td></tr>';
    echo '<tr><td>Planner</td><td>Operations</td><td>Active</td></tr>';
    echo '<tr><td>Live News</td><td>Communications</td><td>Active</td></tr>';
    echo '<tr><td>Content Area</td><td>Management</td><td>Active</td></tr>';
    echo '<tr><td>User Management</td><td>Security</td><td>Active</td></tr>';
} elseif ($type === 'news') {
    echo '<tr><th colspan="4" style="background-color: #a855f7; color: white;">Live News / Announcements Report</th></tr>';
    echo '<tr><th>Title</th><th>Author</th><th>Date Published</th><th>Status</th></tr>';

    $sql = "SELECT title, created_by, created_at, status FROM prtl_portal_announcements ORDER BY created_at DESC";
    $stmt = $conn->query($sql);
    if ($stmt) {
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            $date = $row['created_at'] ? $row['created_at']->format('Y-m-d H:i') : 'N/A';
            echo "<tr><td>{$row['title']}</td><td>{$row['created_by']}</td><td>{$date}</td><td>{$row['status']}</td></tr>";
        }
    }
} elseif ($type === 'status') {
    echo '<tr><th colspan="3" style="background-color: #10b981; color: white;">Portal System Status</th></tr>';
    echo '<tr><th>Component</th><th>Status</th><th>Latency/Load</th></tr>';
    echo '<tr><td>Web Server (XAMPP)</td><td>Online</td><td>Low</td></tr>';
    echo '<tr><td>Database (SQL Server)</td><td>Connected</td><td>Optimal</td></tr>';
    echo '<tr><td>Permissions Engine</td><td>Active</td><td>Healthy</td></tr>';
    echo '<tr><td>Real-time Broadcaster</td><td>Operational</td><td>Active</td></tr>';
} else {
    echo '<tr><th style="background-color: #64748b; color: white;">General Portal Report</th></tr>';
    echo '<tr><td>Date Generated: ' . date('Y-m-d H:i:s') . '</td></tr>';
    echo '<tr><td>Generated By: ' . $_SESSION['username'] . '</td></tr>';
}

echo '</table>';
exit();
